version: "3.8"
services:
  api:
    profiles: ["prod", "dev"]
    container_name: mws-market-api
    image: mws-market-api:latest
    build: 
      context: ./api
      network: host
      dockerfile: Dockerfile
    ports:
      - "18181:18181"
    volumes:
      - "./api:/app"
      - "./creds/:/app/creds"
      # - "./public:/app/public"
    environment:
      - "DOT_ENV=/app/creds/.env"
    command: uvicorn main:app --host 0.0.0.0 --port 18181 --reload
  # api-lint:
  #   profiles: ["dev"]
  #   image: mws-market-api:latest
  #   command: bash -c 'black . ;flake8 --ignore=E501 .'

  frontend:
    profiles: ["prod"]
    container_name: mws-market-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: mws-market-frontend:latest
    ports:
      - "18182:3000"
    command: sh -c 'npm run build && npm run start'
  frontend-dev:
    profiles: ["dev"]
    container_name: mws-market-frontend-dev
    image: mws-market-frontend:latest
    environment:
      - WATCHPACK_POLLING=true 
    ports:
      - "18182:3000"
    volumes:
      - "./frontend:/app"
    command: npm run dev

  rev-proxy:
    image: caddy:2.7.4-alpine
    container_name: mws-market-rev-proxy
    profiles: ["prod"]
    ports:
      - "18180:80"
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile"

  rev-proxy-dev:
    image: caddy:2.7.4-alpine
    container_name: mws-market-rev-proxy-dev
    profiles: ["dev"]
    ports:
      - "18180:80"
    volumes:
      - "./caddy/Caddydev:/etc/caddy/Caddyfile"