import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavAppBar from "@/components/NavAppBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ja">
            <head>
                <link href="https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap" rel="stylesheet" />
            </head>
            <body>
                <div className={inter.className}>
                    <NavAppBar />
                    {children}
                </div>
            </body>
        </html>
    )
}
