import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {AppBar, Toolbar, Typography, Link} from "@mui/material";
import NavAppBar from "@/components/NavAppBar";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    return (
        <div className={inter.className}>
            <NavAppBar/>
            {children}
        </div>
    )
}
